[project]
name = "database-and-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ha1fdan", email = "ha1fdan@ha1fdan.xyz" }
]
requires-python = ">=3.14"
dependencies = [
    "inquirerpy>=0.3.4",
    "prettytable>=3.18.0",
    "pygame-ce>=2.5.8",
]

[project.scripts]
database-and-web = "database_and_web:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
